### ISSUE TITLE
Make the conformance test report lines stable when there are several facts for one line

### ISSUE THREAD

**Issue by netdpb** [jspecify/nullness-checker-for-checker-framework#103]
We could either:
1. Respect the order of the fact comments in the file.
2. Sort the facts.

I propose 1.

**Comment by cpovirk** [comment]
1 sound nicer to me, too. Do we need 2 as a fallback for unexpected facts?

**Comment by netdpb** [comment]
I don't think unexpected fact order matters. We don't write them to the report file at all.

**Comment by cpovirk** [comment]
Ah, right, there's just some kind of per-file "found some unexpected facts," right? I'd been advocating for changing that to individual reports. But until such a thing happens, there is nothing to worry about.
