### ISSUE TITLE
build instructions for main-eisop

### ISSUE THREAD

**Issue by cpovirk** [jspecify/nullness-checker-for-checker-framework#156]
We probably don't need anything officially published, but for those of us who are looking into the branch now, it would be good to have instructions somewhere.

Here's what I originally tried:

```
$ git clone git@github.com:jspecify/jspecify-reference-checker.git && cd jspecify-reference-checker && git checkout main-eisop && ./gradlew assemble
...
git clone git@github.com:jspecify/checker-framework.git ../checker-framework 
Cloning into '../checker-framework'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all task dependencies for configuration ':compileClasspath'.
   > Could not find io.github.eisop:checker:3.42.0-eisop2-SNAPSHOT.
     Searched in the following locations:
       - file:/usr/local/google/home/cpovirk/.m2/repository/io/github/eisop/checker/3.42.0-eisop2-SNAPSHOT/maven-metadata.xml
       - file:/usr/local/google/home/cpovirk/.m2/repository/io/github/eisop/checker/3.42.0-eisop2-SNAPSHOT/checker-3.42.0-eisop2-SNAPSHOT.pom
       - https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/eisop/checker/3.42.0-eisop2-SNAPSHOT/maven-metadata.xml
       - https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/eisop/checker/3.42.0-eisop2-SNAPSHOT/checker-3.42.0-eisop2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/io/github/eisop/checker/3.42.0-eisop2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/io/github/eisop/checker/3.42.0-eisop2-SNAPSHOT/checker-3.42.0-eisop2-SNAPSHOT.pom
     Required by:
         project :
   > Could not find io.github.eisop:checker-qual:3.42.0-eisop2-SNAPSHOT.
...
```

I took a couple guesses and discovered that I should go into `checker-framework` and run `git remote add eisop https://github.com/eisop/checker-framework && git fetch eisop master && git checkout eisop/master` (or some similar command of my preference).

For my current testing purposes, I also switched to use the JSpecify JDK that uses the _old_ package name:

- _After_ the above build, I went into `jdk` and ran `git fetch origin orgjspecifypackage && git checkout FETCH_HEAD`.
- Then I ported https://github.com/jspecify/checker-framework/commit/fd05cda8d44378fa202dd1c264adb8fef6e6a8d3 to my `checker-framework` clone.
- Then I ran a _new_ build in `checker-framework` with `./gradlew buildAll -x cloneAnnotatedJdk -x javadoc -x allJavadoc -Prelease=true`. (Some of those flags are probably unnecessary, but I'm used to running a similar command for improved speed and shading during our releases.)

That gave me something that I was able to start testing against part of Google's codebase. I see some crashes and errors, which I'll look into more tomorrow... :)

(I do note that @netdpb had reported a test problem with `NullSpecTest$Minimal`. I haven't tried to run the tests yet, so I don't know whether it occurs for me.)

**Comment by wmdietl** [comment]
Thanks for testing and the thorough notes! I'm sorry that it was this painful to build :-(

I do not understand why it is cloning `jspecify/checker-framework` for you.
[This line](https://github.com/jspecify/jspecify-reference-checker/pull/155/files#diff-20a4f0cac0de08d955b0369024e7b4de326fde9e0ab5c5cfd4faf6ec6733b627R63) should clone `eisop/checker-framework` and that's what's happening on CI.
Do you understand what's going on?

I'll open a PR to get https://github.com/jspecify/checker-framework/commit/fd05cda8d44378fa202dd1c264adb8fef6e6a8d3 into eisop. Update: I've opened https://github.com/eisop/checker-framework/pull/707.

#154 is about the failure in `NullSpecTest$Minimal` and once that lands in `main-eisop` that should be fixed. That shouldn't impact your testing.

Thanks again!

**Comment by wmdietl** [comment]
@cpovirk Thanks again for raising all these issues.
I think all this has been addressed. Can we close this issue?

**Comment by cpovirk** [comment]
Yes, all appears well now. Thanks!
