### ISSUE TITLE
Unsoundness with array subtyping?

### ISSUE THREAD

**Issue by msridhar** [jspecify/nullness-checker-for-checker-framework#179]
Test case:
```java
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

@NullMarked
class SampleArrays {

  static @Nullable String[] x = new String[1];
  static String[] y = new String[1];

  public static void main(String[] args) {
    x = y;
    x[0] = null;
    y[0].toString();
  }
}
```
This seems to pass the reference checker, but throws an NPE at runtime.

**Comment by cpovirk** [comment]
This reflects the current JSpecify decision to give up and embrace treating arrays as covariant: https://github.com/jspecify/jspecify/issues/65.

Given that the reference checker is still a Checker Framework plugin, you might find that the Checker Framework flag `-AinvariantArrays` can override that. Or you might find that some of the hacks I've put into the plugin have broken that :)

If you'd like to ask for a longer writeup of https://github.com/jspecify/jspecify/issues/65, we might be able to pull that off. I think we mostly concluded that arrays are a special case whose type safety is already broken (by `ArrayStoreException`). But tools could productively try to catch obvious problems (like writing nullable values into an array that originated "elsewhere" and thus might have been covariantly converted from an array of non-nullable values), and I don't think we mean for JSpecify to say that that's not allowed. Notably, Kotlin goes all-in on array invariance, and that's "allowed" in the sense that we don't want to mandate _any_ errors or non-errors. (Depending on how we define "conformance," it may still be a "violation" in the sense that kotlinc doesn't distinguish internally between assignments that would work if arrays _were_ covariant and those that wouldn't work even if they were.) But I guess I can say this and other things in a longer writeup of https://github.com/jspecify/jspecify/issues/65 if you're interested. Please do chime in there if so!

\[edit: I meant to also link to https://github.com/eisop/jdk/pull/85#discussion_r1493138386 (and/or other parts of that PR), which is another recent discussion that touched on array covariance.\]

**Comment by msridhar** [comment]
Thanks for the links and explanation!  Working on this stuff for NullAway so this is very helpful 🙂
