### ISSUE TITLE
Unable to access checker.jar when running the demo

### ISSUE THREAD

**Issue by lbkulinski** [jspecify/nullness-checker-for-checker-framework#84]
Hello

I am currently running into the following error when trying to run `./demo SimpleSample.java`:
```
Error: Unable to access jarfile ./../checker-framework/checker/bin/../dist/checker.jar
```
I am running on macOS 13.4 and am using Corretto 17.0.7.

The build succeeds, and I am using the following commands to run the build:
```
mkdir jspecify
cd jspecify
git clone https://github.com/jspecify/jspecify-reference-checker
cd jspecify-reference-checker
./gradlew assemble
```

Am I doing something wrong (or dumb)? Thanks!

**Comment by wmdietl** [comment]
Hi @lbkulinski ,

Thanks for trying the reference checker! I can reproduce your issue.

@netdpb , I think https://github.com/jspecify/checker-framework/pull/35 broke the initial setup, as now nobody is building the Checker Framework and jspecify repositories for this project.

The temporary work-around is to

````
cd ../checker-framework
./gradlew assemble
cd ../jspecify
./gradlew assemble
cd ../jspecify-reference-checker
./gradlew assemble
./demo SimpleSample.java
````

But clearly, this should happen automatically.

**Comment by lbkulinski** [comment]
@wmdietl Thanks! I'll give that a try.
